version: 2
jobs:

  node-8.11:
    working_directory: ~/app
    docker:
      - image: node:8.11
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: eslint
          command: yarn && yarn eslint .
  
  node-8.10:
    working_directory: ~/app
    docker:
      - image: node:8.10
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: eslint
          command: yarn && yarn eslint .

  publish:
    working_directory: ~/app
    docker:
      - image: node:8.11
    steps:
      - setup_remote_docker
      - checkout
      - run: yarn
      - run:
          name: Tell release-it who is publishing
          command: |
            git config --global user.email $GIT_EMAIL
            git config --global user.name "Rhinogram, LLC"
      - run:
          name: Publish to NPM
          command: yarn release


workflows:
  version: 2

  test:
    jobs:
      - node-8.10:
          filters:
            branches:
              ignore:
                - master
      - node-8.11:
          filters:
            branches:
              ignore:
                - master

  release:
    jobs:
      - node-8.10:
          filters:
            branches:
              only:
                - master
      - node-8.11:
          filters:
            branches:
              only:
                - master
      - publish:
          filters:
            branches:
              only:
                - master
          requires:
            - node-8.11
            - node-8.10
