version: 2
jobs:

  test-8.11:
    working_directory: ~/app
    docker:
      - image: node:8.11
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: eslint
          command: yarn && yarn eslint .
  
  test-8.10:
    working_directory: ~/app
    docker:
      - image: node:8.10
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: eslint
          command: yarn && yarn eslint .

workflows:
  version: 2

  general:
    jobs:
      - test-8.10
      - test-8.11
