version: 2
jobs:

  node-8.11:
    working_directory: ~/app
    docker:
      - image: node:8.11
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: eslint
          command: yarn && yarn eslint .
  
  node-8.10:
    working_directory: ~/app
    docker:
      - image: node:8.10
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: eslint
          command: yarn && yarn eslint .

  publish:
    working_directory: ~/app
    docker:
      - image: node:8.11
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Publish to NPM
          command: |
            echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc
            npm publish


workflows:
  version: 2

  test:
    jobs:
      - node-8.10
      - node-8.11
    filters:
      branches:
        ignore:
          - master

  release:
    jobs:
      - test:
          filters:
            branches:
              only:
                - master
      - publish:
          filters:
            branches:
              only:
                - master
